### ISSUE TITLE
Impossible change Height Island

### ISSUE THREAD

**Issue by DoctaEnkoda** [Iridium-Development/IridiumSkyblock#399]
**Describe the bug**
I tried all the values ​​to change the Y of the creation of the island in schematics.yml.

**To Reproduce**
1. Change value Y
2. Create Island

**Expected behavior**
To be able to put his island at any height.

** Server Version and Plugin Version**
Version : This server is running Purpur version git-Purpur-1383 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6856a5d on ver/1.17.1)
Plugin Name: IridiumSkyblock
[03:47:44 INFO]: Plugin Version: 3.1.1
[03:47:44 INFO]: Plugin Author: Peaches_MLG

** Configuration **

```yml
schematics:
  test:
    item:
      material: "PLAYER_HEAD"
      amount: 1
      displayName: "&b&ltest Island"
      headData: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGY0OTNkZDgwNjUzM2Q5ZDIwZTg0OTUzOTU0MzY1ZjRkMzY5NzA5Y2ViYzlkZGVmMDIyZDFmZDQwZDg2YTY4ZiJ9fX0="
      headOwner: null
      lore:
      - "&7A starter desert island."
      slot: 10
    xHome: -1.5
    yHome: 1.0
    zHome: -0.5
    yawHome: 1.0
    overworld:
      biome: "PLAINS"
      schematicID: "test.iridiumschem"
    nether:
      biome: "NETHER_WASTES"
      schematicID: "test.iridiumschem"
    end:
      biome: "THE_END"
      schematicID: "test.iridiumschem"
```
